Project-OSmOSE/osmose-app

frontend/src/AnnotationCampaignDetail.js, frontend/src/App.js, frontend/src/CreateAnnotationCampaign.js, frontend/src/EditAnnotationCampaign.js, frontend/src/ListChooser.js, frontend/src/css/app.css, frontend/test/AnnotationCampaignDetail.test.js, frontend/test/App.test.js, frontend/test/CreateAnnotationCampaign.test.js, frontend/test/ListChooser.test.js
Add a new page allowing to add annotators to existing campaign.
See task #13
=> feat(campaign): Allow to add annotators to existing campaign

frontend/src/AnnotationCampaignDetail.js
Change name of csv to 'Name_of_campagne_results.csv and 'Name_of__campagne_task_status.csv'
see #45
=> fix csv same name

frontend/src/AudioAnnotator/AudioAnnotator.js, frontend/src/AudioAnnotator/Workbench.js
Last label will be default label for next task.
see #24
=> Remember tag chose

.github/workflows/continuous-integration.yml, .github/workflows/deploy-coverage.yml, README.md
Coverage isn't currently very visible, so let's add a badge and deployment for master.
=> chore(coverage): add automated coverage deployment to github page

frontend/src/AudioAnnotator/Region.js, frontend/src/AudioAnnotator/Workbench.js, frontend/src/css/annotator.css
Begin an annotation in another one.
See #18
=> Annotation in another annotation

backend/api/actions/datawork_import.py
With one query, can add all files to one dataset.
=> Change import : create -> bulk_create

frontend/src/AudioAnnotator/Region.js
The region header changes its place (top to bottom) if the annotation box is on the top of the canvas.
see #19
=> Can delete box on top canva

backend/api/serializers/annotation_campaign.py, backend/api/views/annotation_campaign.py, backend/settings/__init__.py, backend/settings/development.py, backend/urls.py, poetry.lock, pyproject.toml
Fixes https://github.com/Project-ODE/osmose-app/issues/16
=> Fix latency issue on campaign list

backend/api/views/annotation_campaign.py
=> fix(csv reports): fix is_box value for box annotations in whole file mode

frontend/src/AudioAnnotator/Region.js, frontend/src/AudioAnnotator/Workbench.js
Add current zoom to Region component.
Change label position with current zoom and current position.
=> fix css label when zooming

README.md, backend/api/management/commands/seed.py, frontend/package.json, frontend/src/AudioAnnotator/AudioAnnotator.js, poetry.lock, pyproject.toml
Fixes https://github.com/Project-OSmOSE/osmose-app/issues/96 by using https://getbootstrap.com/docs/4.6/components/card/#using-grid-markup
=> fix(annotator): resize footer tag cards

backend/api/migrations/0021_change_zoom_level_format.py, backend/api/views/annotation_campaign.py, backend/tests/fixtures/annotation_campaigns_tasks.yaml, backend/tests/views/annotation_campaign.py
=> filter campaign by annotators

frontend/src/AudioAnnotator/AudioAnnotator.js, frontend/src/AudioAnnotator/AudioPlayer.js
Fixes #143
Test: Check the audio speed select is available.
=> fix(annotator): Audio speed selector (#143)

frontend/src/AudioAnnotator/Workbench.js, frontend/src/css/annotator.css
#79 
Test: When the mouse is over the spectrogram, there is an indicator showing the frequency and time of the mouse coordinates.
The indicator should still show event if the mouse is over annotation boxes
=> feat(annotator): add frequency indicator

backend/api/actions/check_new_spectro_config_errors.py, backend/api/actions/datawork_import.py
#121 
Test: put the dataset in a campaign directory and complete the folder_name in dataset.csv ('campaign/dataset')
The dataset should stay available in Aplose
=> feat(back): add ability to put dataset folders in campaign folder

.github/workflows/continuous-integration.yml, .gitlab-ci.yml, README.md, backend/api/management/commands/seed.py, backend/start.sh
Bump version and improve some workflows
=> deploy(1.6.0): bump version plus small updates

.gitlab-ci.yml, website/src/pages/Home/HomePage.tsx, website/src/pages/News/NewsDetail/NewsDetailPage.tsx, website/src/pages/News/NewsPage.tsx, website/src/pages/People/People.tsx, website/src/pages/People/PeopleDetail/PeopleDetail.tsx, website/src/pages/Projects/ProjectDetail/ProjectDetail.tsx, website/src/pages/Projects/Projects.tsx
> Bonjour,
> 
> le backend et le front en v1.7.0 sont déployés.
> 
> Il y a un problème au vu du nombre de requêtes qui sont réalisées sur la page d'accueil (visible en activant la console web dans le navigateur).
> 
> Par ailleurs, les autres pages semblent vide de contenu et le client web bombarde l'API.
> 
> Je n'ai pas fait de rollback pour le moment. S'il faut redéployer la version précédente dite le moi.
> 
> Bonne journée,
=> fix(website): too many requests

.github/workflows/cypress.yml, backend/api/management/commands/seed.py, frontend/cypress/e2e/0-APLOSE/1 - login.cy.js, frontend/cypress/e2e/0-APLOSE/2 - datasets.cy.js, frontend/cypress/e2e/0-APLOSE/3 - campaigns.cy.js, frontend/cypress/e2e/0-APLOSE/4 - campaign creation.cy.js, frontend/cypress/e2e/0-APLOSE/5 - whole file campaign.cy.js, frontend/cypress/support/commands.js
This fixes Cypress tests, it also adds Cypress session usage which caches logins and speeds up tests.
=> chore(CI): Fix CI cypress testing

frontend/vite.config.ts, package.json, website/package-lock.json, website/package.json, website/src/components/Banner/index.tsx, website/src/components/Card/index.tsx, website/src/components/DetailPage/DetailPage.tsx, website/src/components/Layout/index.tsx, website/src/components/PageTitle/index.tsx, website/src/pages/Explore/index.tsx, website/src/pages/Ontology/index.tsx, website/src/pages/Publications/index.tsx
Add recent publications
Must update dependencies because of react not recognizing react-router-dom component as JSX elements (don't no why now..)
=> Add recent publications

frontend/src/App.tsx, frontend/src/css/ionic-override.css, frontend/src/view/audio-annotator/components/bloc/confidence-indicator-bloc.component.tsx
Add a checkmark on the selected item
=> feat(annotator): Improve comprehension of the selected confidence

frontend/src/components/form/inputs/input.tsx, frontend/src/services/annotator/spectrogram.service.ts, frontend/src/services/utils/format.tsx
Images doesn't load. They aren't even requested.
=> fix(1.12.3): spectrogram images loading & input min/max

backend/api/serializers/annotation/result.py, backend/api/tests/serializers/annotation/result.py, backend/api/views/annotation/result.py, pyproject.toml
cannot submit annotation result without confidence indicator in campaign without confidence indicator set
=> FIX: Annotation result submission

backend/api/views/annotation/campaign.py, backend/api/views/annotation/file_range.py
Two issues:
- The campaign was shown multiple times in list
- Only first file range files were shown in detail
=> fix(file-range): Multiple file ranges handling [ADEV-201, ADEV-202]

frontend/src/view/dataset/ImportModal.tsx
The component wasn't responding correctly due to duplicated keys in map
=> fix(dataset): Search a dataset to import doesn't work [ADEV-214]
